version: "3.7"
services:
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password

  fluxbb:
    build: ./
    image: fluxbb:latest
    volumes:
      - ./config.php:/var/www/html/config.php
    ports:
      - 8080:80
